version: '3'

services:
  dashboard_service:
    container_name: dashboard_service
    build: dashboard_service
    volumes:
      - ./dashboard_service:/app
    ports:
      - "8001:8001"
    env_file:
      - app_dashboard.env
    networks:
      - dashboard_network

  register_service:
    container_name: register_service
    build: register_service
    volumes:
      - ./register_service:/app
    ports:
      - "8002:8002"
    env_file:
      - app_register.env
    networks:
      - register_network

  mongo:
    container_name: mongo-db
    image: mongo:5.0
    ports:
      - "27019:27017"
    volumes:
      - ./dashboard_service/app/db/data:/data/db
    networks:
      - default

  nginx:
    container_name: fastapi_revers_proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard_service
      - register_service
    networks:
      - default
      - dashboard_network
      - register_network

networks:
  default:
    external:
      name:
        microservice_network

  dashboard_network:
    external:
      name: dashboard_network

  register_network:
    external:
      name: register_network

