version: '3'

services:
  dashboard_service:
    container_name: dashboard_service
    build: dashboard_service
    command: uvicorn app.main:app --port 8000 --host 0.0.0.0 --reload
    volumes:
      - ./dashboard_service:/app
    ports:
      - "8001:8000"
#    env_file:
#      - app_dashboard.env

  register_service:
    container_name: register_service
    build: register_service
    command: uvicorn app.main:app --port 8000 --host 0.0.0.0 --reload
    volumes:
      - ./register_service:/app
    ports:
      - "8002:8000"
#    env_file:
#      - app_register.env

#  dashboard_db:
#    container_name: dashboard_db
#    image: mongo:5.0
#    volumes:
#      - mongodb_data_dashboard:/var/lib/mongodb/data/
#
#  register_db:
#    container_name: register_db
#    image: mongo:5.0
#    volumes:
#      - mongodb_data_register:/var/lib/mongodb/data/

  nginx:
    container_name: fastapi_revers_proxy
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./.nginx_config:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard_service
      - register_service


